import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Tajawal } from "next/font/google"; // Import Tajawal
import "./globals.css";
import { getDirection } from '../lib/i18n';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  subsets: ['arabic'],
  weight: ['400', '500', '700'],
  variable: '--font-tajawal',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale = 'en' },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: 'en' | 'ar' };
}>) {
  const dir = getDirection(locale);

  const bodyClasses = [
    geistSans.variable,
    geistMono.variable,
    tajawal.variable,
    'antialiased',
    locale === 'ar' ? 'font-ar' : 'font-en',
  ].join(' ');

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body className={bodyClasses}>
        {children}
      </body>
    </html>
  );
}